development:
  adapter: postgresql
  database: shoes_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: shoes_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: shoes_production
  pool: 5
  timeout: 5000
